# Generated by Django 5.0.6 on 2024-07-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
