# Generated by Django 5.0.6 on 2024-07-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_ordernumber_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
    ]
